name: 'AWS Infrastructure Pipeline'

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  aws-plan:
    if: github.event_name == 'pull_request'
    uses: zubayr-nonprod-org/iac-shared-workflows/.github/workflows/tf-aws-template.yml@main
    with:
      environment: 'staging-aws'
      is_apply: false
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

  aws-apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: zubayr-nonprod-org/iac-shared-workflows/.github/workflows/tf-aws-template.yml@main
    with:
      environment: 'production-aws'
      is_apply: true
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
