name: 'Azure Infrastructure Pipeline'

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  azure-plan:
    if: github.event_name == 'pull_request'
    uses: zubayr-nonprod-org/iac-shared-workflows/.github/workflows/terraform/tf-azure-template.yml@main
    with:
      environment: 'staging-azure'
      is_apply: false
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  azure-apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: zubayr-nonprod-org/iac-shared-workflows/.github/workflows/terraform/tf-azure-template.yml@main
    with:
      environment: 'production-azure'
      is_apply: true
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
